nav:
  - Home:
    - SenDNN Inference Plugin: README.md
    - Roadmap: roadmaps/q3-2025.md
    - Getting Started:
      - Installation: getting_started/installation.md
    - Deploying:
      - Docker: deploying/docker.md
      - Kubernetes: deploying/k8s.md
      - Red Hat OpenShift AI: deploying/rhoai.md
    - Examples:
      - Offline Inference: examples/offline_inference
      - Online Inference: examples/online_inference
    - User Guide:
      - Configuration: user_guide/configuration.md
      - Environment Variables: user_guide/env_vars.md
      - Supported Features: user_guide/supported_features.md
      - Supported Models: user_guide/supported_models.md
      - Performance Tuning: user_guide/performance.md
    - Developer Guide:
      - Contributing: contributing/README.md
      - Maintaining: contributing/maintaining.md
      - Design Documents:
        - Architecture: contributing/architecture.md
        - Scheduling & Padding: contributing/scheduler.md
        - MultiModal:
          - Adding New Models: contributing/multimodal/adding_new_models.md

  - Getting Started:
    - Installation: getting_started/installation.md
  - Deploying:
    - Docker: deploying/docker.md
    - Kubernetes: deploying/k8s.md
    - Red Hat OpenShift AI: deploying/rhoai.md
  - User Guide:
    - Configuration: user_guide/configuration.md
    - Environment Variables: user_guide/env_vars.md
    - Supported Features: user_guide/supported_features.md
    - Supported Models: user_guide/supported_models.md
    - Performance Tuning: user_guide/performance.md
  - Developer Guide:
    - Contributing: contributing/README.md
    - Maintaining: contributing/maintaining.md
    - Design Documents:
      - Architecture: contributing/architecture.md
      - Scheduling & Padding: contributing/scheduler.md
      - MultiModal:
        - Adding New Models: contributing/multimodal/adding_new_models.md
